@host = http://127.0.0.1:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc2NjIzMjEzN30.-Gtv2NyySFuHzsEaSuk2gMgDX1y9tn-bQMUtbk0N4mw

POST {{host}}/api/user/query

### login

POST {{host}}/api/user/token
Content-Type: application/x-www-form-urlencoded

username=admin&password=secret

### global header

GET {{host}}/api/user/me
Authorization: Bearer {{token}}


### 获取文章列表

POST {{host}}/api/blog/query

### 创建文章

POST {{host}}/api/blog/create
Authorization: Bearer {{token}}

{
    "title": "标题",
    "category_name": "分类",
    "summary": "摘要",
    "content_rich": "正文"
}


### 更新文章

PUT {{host}}/api/blog/detail/1

{
    "title": "标题111",
    "summary": null
}

### 获取文章详情

GET {{host}}/api/blog/detail/1


### 删除文章

DELETE {{host}}/api/blog/detail/1

